---
apiVersion: v1
kind: Service
metadata:
  annotations:
    externalTrafficPolicy: Local
  name: lb-test
  namespace: default
spec:
  externalIPs:
  - 1.2.3.4
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
  selector:
    app: nginx-ingress
    component: controller
    release: public-ingress
  type: LoadBalancer
