---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-template
  namespace: default
data:
  template: |
    {{- $v := get "-n" "default" "configmaps" -}}
    {{- range $v -}}
    {{- if eq .metadata.name "loadbalancer-config" -}}
    {{- render "lb-renderer" .data.template -}}
    {{- end -}}
    {{- end -}}
